version: '3.8'
services:
  backendapi:
    build: 
      context: .
    image: vmsi
    ports: 
      - "8080:8080"
    volumes:
      - type: bind
        source: VoiceMessages
        target: /App/VoiceMessageFiles